### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by shibuML** [satendrapandeymp/Fb_details_scrapper#1]
File "Main.py", line 49
    print getDetailsAboutGivenUser({'isCustomUrl': True, 'userId': u'rhythmpathak'})
                                 ^
SyntaxError: invalid syntax

**Comment by surafelkifetew1** [comment]
File "Main.py", line 49
print getDetailsAboutGivenUser({'isCustomUrl': True, 'userId': u'rhythmpathak'})
^
SyntaxError: invalid syntax

similar problem any help ??

**Comment by satendrapandeymp** [comment]
This code was written for python 2.x. So You can either use python 2.x to run it or just do some minor modifications here and there to make it compatible with python 3.x
In case you do some changes to make it compatible with python 3.x, Please create a PR.
Cheers
